# Generated by Django 4.0.2 on 2022-03-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_feedback_user_newsfeed_user_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
