# Generated by Django 4.0.2 on 2022-03-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_blog_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='outDesc',
            field=models.TextField(default='WAILUKU – After chances to get treatment through probation and the Maui Drug Court, a Wailuku man was resentenced to five years in prison. Devin Ferreira, 31, had asked for another chance on probation March 24, saying he was ready to participate in another treatment program. But 2nd Circuit Judge Kelsey Kawano said a review of Ferreira’s history “leads the court to believe you are not a suitable candidate for probation.” “Maui Drug Court is the most controlled, structured program the Judiciary can offer,” Kawano said. “The courts sees in your record an unchanging attitude with regard to resistance to treatment. At Ferreira’s resentencing March 24, Deputy Prosecutor Kenton Werk said the defendant’s criminal history includes four felony and eight misdemeanor convictions. Ferreira’s involvement with the criminal justice system started in 2011 when he was 20 and successfully completed a deferral for fourth-degree theft, Werk said. He said Ferreira’s first felony convictions occurred in 2015 in two cases. He was sentenced to a six-month jail term as part of probation for three counts of second-degree theft and third-degree promotion of a dangerous drug. About a year after being placed on probation, Ferreira had stopped reporting and was using drugs, Werk said. Ferreira was resentenced in November 2016 to a year in jail. In late 2020, he was again facing revocation of his probation before being admitted into the Drug Court program of intensive treatment and supervision in March 2021, Werk said. Ferreira spent nine months in the program “but never really engaged in the treatment being offered,” Werk said. “He continued to use drugs and attempted to conceal his use by tampering with his samples,” Werk said. While the prosecution recommended that Ferreira be resentenced to five-year prison terms, to be served at the same time, the defendant asked the court to consider another term of probation. While Ferreira was in Drug Court, “even though he was not ultimately successful, he got a taste of what it means to be a productive member of society,” said Deputy Public Defender Brad Sova. “The reality is he has spent the majority of his adult life dealing with the fallout of his addiction,” Sova said. “Even though we see many stumbles, we do see he made positive progress in his sobriety during that time.” He said Ferreira had tried to reenter Drug Court and wanted to support his young daughter. “The reality of addiction is that old habits die hard,” Sova said. “He did relapse. Unfortunately, he also succumbed to criminal thinking.” After he was initially dishonest about relapsing, Ferreira was terminated from participation in Drug Court, Sova said. Kawano said Ferreira could seek drug treatment while in prison.'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=models.TextField(),
        ),
    ]
